<?php
/**
 * @file
 * Main implementation file for Thing One.
 */
include_once 'includes/thing_one.entity.inc';

/**
 * Implements hook_entity_info().
 */
function thing_one_entity_info() {
  $entity_info = array();

  $entity_info['blog'] = array(
    // The basics.
    'label' => t('Blog'),
    'base table' => 'blog',
    'module' => 'thing_one',
    'load hook' => 'blog_load',
    'access callback' => 'thing_one_access_callback',
    'uri callback' => 'entity_class_uri',

    // Allow users to add fields to an entity instance.
    'fieldable' => TRUE,

    // Provide a single, default bundle.
    'bundles' => array(
      'blog' => array(
        'label' => t('Project'),
        'admin' => array(
          'path' => 'admin/blogs',
        )
      ),
    ),

    // Use common pattern for id and label.
    'entity keys' => array(
      'id' => 'id',
      'label' => 'title',
    ),

    // Custom backend and controller.
    'entity class' => 'BlogEntity',
    'controller class' => 'BlogEntityController',

    // Admin UI. Let drupal help us with the default UI controller.
    'admin ui' => array(
      'path' => 'admin/blogs',
      'controller class' => 'EntityDefaultUIController',
    ),

  );

  return $entity_info;
}

/**
 * Implements hook_menu().
 */
function thing_one_menu() {
  $items = array();

  // View a single blog.
  $blog_uri = 'blog/%blog';
  $blog_id_arg_position = 1;
  $items[$blog_uri] = array(
    'title callback' => 'entity_label',
    'title arguments' => array('blog', $blog_id_arg_position),
    'page callback' => 'blog_view',
    'page arguments' => array($blog_id_arg_position),
    'access arguments' => array('access content'),
    'file' => 'includes/thing_one.pages.inc',
  );

  // View a blog listing.
  $Items['blogs'] = array(
    'title' => 'Blogs',
    'page callback' => 'thing_one_blog_listing_view',
    'access arguments' => array('access content'),
    'file' => 'includes/thing_one.pages.inc',
  );

  return $items;
}

/**
 * Access callback for Blog instances.
 */
function thing_one_access_callback($op, $blog = NULL, $account = NULL) {
  // Serious placeholder for real access checks.
  return true;
}


