<?php
/**
 * @file
 * Main implementation file for Thing One.
 */

/**
 * Implements hook_entity_info().
 */
function thing_one_entity_info() {
  $entity_info = array();

  $entity_info['blog'] = array(
    // The basics.
    'label' => t('Blog'),
    'base table' => 'blog',
    'module' => 'thing_one',
    'access callback' => 'thing_one_access_callback',
    'uri callback' => 'entity_class_uri',

    // Allow users to add fields to an entity instance.
    'fieldable' => TRUE,

    // Provide a single, default bundle.
    'bundles' => array(
      'blog' => array(
        'label' => t('Project'),
        'admin' => array(
          'path' => 'admin/blogs',
        )
      ),
    ),

    // Use common pattern for id and label.
    'entity keys' => array(
      'id' => 'id',
      'label' => 'title',
    ),

    // Custom backend and controller.
    'entity class' => 'BlogEntity',
    'controller class' => 'BlogEntityController',

    // Admin UI. Let drupal help us with the default UI controller.
    'admin ui' => array(
      'path' => 'admin/blogs',
      'controller class' => 'EntityDefaultUIController',
    ),

  );

  return $entity_info;
}

/**
 * Implements hook_menu().
 */
function thing_one_menu() {
  $items = array();

  // View a single blog.
  $items['blog/%'] = array(
    'title' => 'Blog',
    'page callback' => 'thing_one_view_blog',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
    'file' => 'includes/thing_one.pages.inc',
  );

  return $items;
}

/**
 * Access callback for Blog instances.
 */
function thing_one_access_callback($op, $blog = NULL, $account = NULL) {
  // Serious placeholder for real access checks.
  return true;
}

/**
 * Implements hook_form() for the Blog entity.
 *
 * Admin UI for creating or updating a blog.
 */
function blog_form($form, &$form_state, $blog = NULL) {
  $form = array();

  $form['title'] = array(
    '#title' => t('Project name'),
    '#type' => 'textfield',
    '#default_value' => isset($blog->title) ? $blog->title : '',
    '#required' => TRUE,
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => isset($blog->id) ? t('Update project') : t('Save project'),
    '#weight' => 50,
  );

  return $form;
}

/**
 * Implements hook_form_submit().
 */
function blog_form_submit($form, &$form_state) {
  // Save or update.
  $blog = entity_ui_form_submit_build_entity($form, $form_state);
  $blog->save();

  // Inform the user.
  drupal_set_message(t('The blog @title has been saved.', array(
    '@title' => $blog->title
  )));

  // Go to the admin UI landing page.
  $form_state['redirect'] = 'admin/blogs';
}
